# Generated by Django 4.2.9 on 2025-12-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cartitem_unique_together_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_download_url',
            field=models.URLField(blank=True, help_text='Third-party download URL (if provided, this will be used instead of digital_file)', max_length=500, null=True),
        ),
    ]
